## Start from base perl
FROM perl:5.20
MAINTAINER erictdawson

## Install bioperl
## and DB::Sam

## Install blat

## Install CAP3

## Get CREST and unpack the tarball

## Link in the dependencies and build crest

## Make a symbolic link for easy access
